# Validation diagnostics for impurity and DMFT calculations.

"""Maximum absolute self-energy for a nominally noninteracting impurity result."""
noninteracting_self_energy_residual(result::ImpuritySolverResult) = maximum(abs.(result.self_energy.values); init=0.0)

"""Relative mismatch between the converged impurity and lattice Green functions."""
function impurity_local_residual(result::DMFTResult)
    impurity = result.impurity_result.green_function
    lattice_green_function = result.local_green_function
    _compatible_frequency_objects(impurity, lattice_green_function)
    numerator = maximum(abs.(impurity.values .- lattice_green_function.values); init=0.0)
    denominator = max(maximum(abs.(impurity.values); init=0.0), maximum(abs.(lattice_green_function.values); init=0.0), 1.0)
    return numerator / denominator
end

"""Half-filled atomic Hubbard Green function `G(iω)=iω/[(iω)²-(U/2)²]` for `ε_d=0` and `μ=U/2`."""
function atomic_hubbard_green(axis::FermionicMatsubaraAxis, interaction::Real)
    U = Float64(interaction)
    values = ComplexF64[axis[i] / (axis[i]^2 - (U / 2)^2) for i in 1:length(axis)]
    return GreenFunction(axis, values; labels=[:impurity], metadata=Dict{Symbol,Any}(:limit => :atomic_half_filled))
end

"""Half-filled atomic Hubbard self-energy `Σ(iω)=U/2+U²/(4iω)` for `ε_d=0` and `μ=U/2`."""
function atomic_hubbard_self_energy(axis::FermionicMatsubaraAxis, interaction::Real)
    U = Float64(interaction)
    values = ComplexF64[U / 2 + U^2 / (4 * axis[i]) for i in 1:length(axis)]
    return SelfEnergy(axis, values; labels=[:impurity], metadata=Dict{Symbol,Any}(:limit => :atomic_half_filled))
end

"""Relative `L²` discrepancy between a target hybridization and the hybridization generated by a finite ED bath."""
function bath_discretization_residual(target::HybridizationFunction, bath::DiscreteBath; chemical_potential::Real=0.0)
    fitted = hybridization_function(bath, target.axis; chemical_potential=chemical_potential)
    _compatible_frequency_objects(target, fitted)
    numerator = norm(fitted.values - target.values)
    return numerator / max(norm(target.values), eps(Float64))
end

"""Relative violation of particle-hole pairing in a finite bath, measured about the supplied chemical potential."""
function bath_particle_hole_residual(bath::DiscreteBath; chemical_potential::Real=0.0)
    isempty(bath.energies) && return 0.0
    permutation = sortperm(bath.energies)
    offsets = bath.energies[permutation] .- Float64(chemical_potential)
    couplings = abs.(bath.hybridizations[permutation])
    residual = 0.0
    for p in 1:(length(bath) ÷ 2)
        q = length(bath) + 1 - p
        residual = max(residual, abs(offsets[p] + offsets[q]), abs(couplings[p] - couplings[q]))
    end
    isodd(length(bath)) && (residual = max(residual, abs(offsets[(length(bath) + 1) ÷ 2])))
    scale = max(maximum(abs.(offsets); init=0.0), maximum(couplings; init=0.0), 1.0)
    return residual / scale
end

"""Relative difference between the lowest positive-frequency values of two compatible self-energies."""
function low_frequency_self_energy_residual(reference::SelfEnergy, candidate::SelfEnergy; nfrequencies::Integer=min(8, length(reference)))
    _compatible_frequency_objects(reference, candidate)
    nfrequencies > 0 || throw(ArgumentError("nfrequencies must be positive"))
    positive = [i for i in 1:length(reference) if imag(reference.axis[i]) > 0]
    isempty(positive) && throw(ArgumentError("low-frequency self-energy validation requires positive Matsubara frequencies"))
    sort!(positive; by=i -> imag(reference.axis[i]))
    selected = positive[1:min(Int(nfrequencies), length(positive))]
    numerator = norm(candidate.values[:, :, selected] - reference.values[:, :, selected])
    denominator = max(norm(reference.values[:, :, selected]), 1.0)
    return numerator / denominator
end

"""
    bethe_self_consistency_residual(lattice, G, G0; chemical_potential=0)

Relative residual of the Bethe-lattice identity `G₀⁻¹(iω)=iω+μ-t²G(iω)` with `t=D/2`, where `D` is the semicircular half-bandwidth.
"""
function bethe_self_consistency_residual(lattice::BetheLattice, G::GreenFunction, G0::NonInteractingGreenFunction; chemical_potential::Real=0.0)
    _compatible_frequency_objects(G, G0)
    matrix_dimension(G) == 1 || throw(DimensionMismatch("Bethe self-consistency validation currently supports scalar Green functions"))
    hopping = lattice.half_bandwidth / 2
    residual = 0.0
    scale = 0.0
    for i in 1:length(G)
        lhs = inv(G0[1, 1, i])
        rhs = G.axis[i] + chemical_potential - hopping^2 * G[1, 1, i]
        residual = max(residual, abs(lhs - rhs))
        scale = max(scale, abs(lhs), abs(rhs))
    end
    return residual / max(scale, 1.0)
end

"""
    quasiparticle_weight_estimate(Σ; nfit=4)

Estimate the Fermi-liquid quasiparticle weight from the low-frequency Matsubara slope `Im Σ(iω) ≈ (1 - 1/Z)ω`. This diagnostic is meaningful only when the low-frequency self-energy is in a Fermi-liquid regime.
"""
function quasiparticle_weight_estimate(sigma::SelfEnergy; nfit::Integer=min(4, length(sigma)))
    matrix_dimension(sigma) == 1 || throw(DimensionMismatch("quasiparticle-weight estimation currently supports a scalar self-energy"))
    positive = [i for i in 1:length(sigma) if imag(sigma.axis[i]) > 0]
    isempty(positive) && throw(ArgumentError("quasiparticle-weight estimation requires positive Matsubara frequencies"))
    sort!(positive; by=i -> imag(sigma.axis[i]))
    count = min(Int(nfit), length(positive))
    count >= 1 || throw(ArgumentError("nfit must be positive"))
    selected = positive[1:count]
    omega = Float64[imag(sigma.axis[i]) for i in selected]
    imaginary_self_energy = Float64[imag(sigma[1, 1, i]) for i in selected]
    denominator = dot(omega, omega)
    denominator > 0 || throw(ArgumentError("Matsubara frequencies must be nonzero"))
    slope = dot(omega, imaginary_self_energy) / denominator
    weight = inv(1 - slope)
    return (weight=weight, slope=slope, frequencies=omega, values=imaginary_self_energy)
end

"""Collect convergence, closure, causality, particle-hole, and limiting-case diagnostics for a DMFT result."""
function validate_dmft_result(result::DMFTResult)
    diagnostics = Dict{Symbol,Any}(
        :converged => result.converged,
        :termination => get(result.metadata, :termination, result.converged ? :converged : :maxiter),
        :fixed_point_residual => result.residual,
        :final_residual => get(result.metadata, :final_residual, result.residual),
        :final_iteration_residual => get(result.metadata, :final_iteration_residual, isempty(result.history) ? Inf : result.history[end].residual),
        :best_residual => get(result.metadata, :best_residual, result.residual),
        :best_iteration_residual => get(result.metadata, :best_iteration_residual, get(result.metadata, :best_residual, result.residual)),
        :iteration_of_best_residual => get(result.metadata, :iteration_of_best_residual, result.iterations),
        :closure_residual => get(result.metadata, :closure_residual, NaN),
        :residual_history => Float64[entry.residual for entry in result.history],
        :weiss_residual_history => Float64[entry.weiss_residual for entry in result.history],
        :hybridization_residual_history => Float64[entry.hybridization_residual for entry in result.history],
        :bath_fit_residual_history => Float64[entry.bath_fit_residual for entry in result.history],
        :mixing_alpha_history => Float64[entry.mixing_alpha for entry in result.history],
        :impurity_local_residual => impurity_local_residual(result),
        :local_causality_residual => causality_residual(result.local_green_function),
        :impurity_causality_residual => causality_residual(result.impurity_result.green_function),
        :self_energy_causality_residual => causality_residual(result.self_energy),
        :bath_discretization_residual => bath_discretization_residual(result.hybridization, result.impurity_result.bath;
                                                                      chemical_potential=result.problem.chemical_potential),
        :bath_particle_hole_residual => bath_particle_hole_residual(result.impurity_result.bath; chemical_potential=result.problem.chemical_potential),
    )
    if result.problem.lattice isa BetheLattice
        diagnostics[:bethe_self_consistency_residual] = bethe_self_consistency_residual(result.problem.lattice, result.local_green_function,
                                                                                        result.weiss_green_function;
                                                                                        chemical_potential=result.problem.chemical_potential)
    end
    if iszero(result.problem.interaction)
        diagnostics[:noninteracting_self_energy_residual] = maximum(abs.(result.self_energy.values); init=0.0)
    end
    half_filled = isapprox(result.problem.chemical_potential, result.problem.impurity_energy + result.problem.interaction / 2; rtol=1e-12, atol=1e-12)
    if half_filled && all(index -> (-index - 1) in result.problem.axis.indices, result.problem.axis.indices)
        diagnostics[:green_particle_hole_residual] = particle_hole_symmetry_residual(result.impurity_result.green_function)
        diagnostics[:self_energy_particle_hole_residual] = particle_hole_symmetry_residual(result.self_energy; center=result.problem.interaction / 2)
    end
    if result.problem.lattice isa AtomicLattice &&
       isapprox(result.problem.lattice.onsite_energy, result.problem.impurity_energy; rtol=1e-12, atol=1e-12) && half_filled
        expected_green = atomic_hubbard_green(result.problem.axis, result.problem.interaction)
        expected_self_energy = atomic_hubbard_self_energy(result.problem.axis, result.problem.interaction)
        diagnostics[:atomic_green_residual] = norm(result.impurity_result.green_function.values - expected_green.values) / max(norm(expected_green.values), 1.0)
        diagnostics[:atomic_self_energy_residual] = self_energy_residual(expected_self_energy, result.self_energy)
    end
    return diagnostics
end
