"""Root type for all operator algebras."""
abstract type AbstractOperatorAlgebra end

"""Spin algebra generated by local spin operators."""
struct SpinAlgebra <: AbstractOperatorAlgebra
    nsites::Int

    function SpinAlgebra(nsites::Integer)
        nsites < 0 && throw(ArgumentError("nsites must be nonnegative"))
        new(Int(nsites))
    end
end

"""Canonical bosonic commutation algebra."""
struct BosonAlgebra <: AbstractOperatorAlgebra
    nmodes::Int

    function BosonAlgebra(nmodes::Integer)
        nmodes < 0 && throw(ArgumentError("nmodes must be nonnegative"))
        new(Int(nmodes))
    end
end

"""Canonical fermionic anticommutation algebra."""
struct FermionAlgebra <: AbstractOperatorAlgebra
    nmodes::Int

    function FermionAlgebra(nmodes::Integer)
        nmodes < 0 && throw(ArgumentError("nmodes must be nonnegative"))
        new(Int(nmodes))
    end
end

"""Clifford algebra generated by Hermitian Majorana operators."""
struct MajoranaAlgebra <: AbstractOperatorAlgebra
    ngenerators::Int

    function MajoranaAlgebra(ngenerators::Integer)
        ngenerators < 0 && throw(ArgumentError("ngenerators must be nonnegative"))
        iseven(ngenerators) || throw(ArgumentError("Majorana generators should occur in pairs"))
        new(Int(ngenerators))
    end
end

"""Canonical coordinate-momentum algebra `[x_i,p_j] = i*hbar*delta_ij`."""
struct CoordinateMomentumAlgebra <: AbstractOperatorAlgebra
    ndof::Int

    function CoordinateMomentumAlgebra(ndof::Integer)
        ndof < 0 && throw(ArgumentError("ndof must be nonnegative"))
        new(Int(ndof))
    end
end

"""Tensor-product/composite operator algebra."""
struct CompositeAlgebra{A<:Tuple} <: AbstractOperatorAlgebra
    factors::A

    function CompositeAlgebra(factors::A) where {A<:Tuple}
        all(x -> x isa AbstractOperatorAlgebra, factors) ||
            throw(ArgumentError("all composite factors must be operator algebras"))
        new{A}(factors)
    end
end

CompositeAlgebra(algebras::AbstractOperatorAlgebra...) = CompositeAlgebra(tuple(algebras...))

"""Human-readable statistics/algebra family tag."""
algebra_kind(::SpinAlgebra) = :spin
algebra_kind(::BosonAlgebra) = :boson
algebra_kind(::FermionAlgebra) = :fermion
algebra_kind(::MajoranaAlgebra) = :majorana
algebra_kind(::CoordinateMomentumAlgebra) = :coordinate_momentum
algebra_kind(::CompositeAlgebra) = :composite
